import Head from "next/head";
import Image from "next/image";

import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/apollo.jpg";
import lightBulb from "../../public/images/svgs/greenRocket.svg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Apollo Detalo&#39;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Apollo Detalo"
                className="w-full h-auto rounded-3xl p-5 lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, 
                (max-width: 1200px) 50vw, 
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Aspiring and self-motivated developer passionate about creating
                customized interfaces that prioritize accessibility,
                responsiveness, and security. Organized and adept at meeting
                simultaneous deadlines. Actively stays up to date with
                technology trends to implement best practices in web design.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/APOLLO DETALO - CV.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-solid border-2 border-transparent hover:border-nvidia 
                  
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:px-2 md:text-base "
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:apollodetalo90@gmail.com"
                  target={"_blank"}
                  className="hover:text-nvidia ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt="Apollo Detalo"
            className="w-full h-auto"
          />
          <p className="text-center dark:text-loadinggreen ">let&#39;s go!</p>
        </div>
      </main>
    </>
  );
}
